version: "3.8"

services:
  json2video:
    build: .
    container_name: json2video
    ports:
      - "5003:5003"
    volumes:
      - ./cache:/app/cache
      - ./movies:/app/movies
    environment:
      - FLASK_APP=run.py
      - PUBLIC_PORT=${MOVIES_PUBLIC_PORT}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
