FROM python:3.8-slim

WORKDIR /app

RUN apt-get update && apt-get install -y ffmpeg

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN pip install docker

COPY . .

CMD ["pytest"]
