version: '3.8'

services:
  json2video:
    build: .
    container_name: json2video
    ports:
      - "5003:5003"
    volumes:
      - ./movies:/app/movies
    environment:
      - FLASK_APP=app.py
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

